openapi: 3.0.0
info:
  title: Example API
  version: 1.0.0
  description: This is a simple test API for SpecLens ingestion.
servers:
  - url: http://localhost:8000
paths:
  /hello:
    get:
      summary: Say Hello
      description: Returns a simple greeting message.
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Hello, World!
  /goodbye:
    post:
      summary: Say Goodbye
      description: Returns a farewell message.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: John
      responses:
        '200':
          description: Successful response
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: Goodbye, John!
